
server {
        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;
        #   Indique à Nginx d'écouter les connexions entrantes sur le port 443, qui est le port par défaut pour les connexions HTTPS sécurisées.
        #   L'ajout de "ssl" active la prise en charge SSL/TLS pour ces connexions.
        #   Spécifie également l'écoute sur toutes les interfaces IPv6 (::).

	    server_name cben-bar.42.fr;
        #   Indique que cette config s'applique aux requêtes HTTP/HTTPS qui sont destinées à ce nom de domaine spécifique.

    	autoindex on;
        #   Nginx génère une liste des fichiers présents dans un répertoire lorsqu'un utilisateur accède à ce répertoire via le navigateur.
        #   Cette liste des fichiers est affichée à l'utilisateur, lui permettant de naviguer et de télécharger les fichiers.

    	ssl    on;
	    ssl_protocols TLSv1.2 TLSv1.3;                          #   Spécifie les protocoles SSL/TLS pris en charge.
	    ssl_certificate    		/etc/ssl/cben-bar.42.fr.crt;    #   Indique le chemin du fichier de certificat SSL utilisé pour le site.
	    ssl_certificate_key		/etc/ssl/cben-bar.42.fr.key;    #   Spécifie le chemin de la clé privée correspondant au certificat SSL.

        root /var/www/html/wordpress;
        #   Nginx utilisera ce répertoire racine pour localiser les fichiers HTML, CSS, JavaScript
        #   et autres fichiers nécessaires à l'affichage du site.

        index index.php index.html index.htm index.nginx-debian.html;
        #   Définit l'ordre de recherche des fichiers d'index par le serveur Nginx lorsqu'il reçoit une requête

        location / {
                try_files $uri $uri/ =404;
        }
        #   Indique à Nginx de gérer les requêtes pour le chemin racine ("/") en essayant de trouver les fichiers demandés
        #   ou un fichier d'index correspondant. Si aucun fichier n'est trouvé, il renverra une erreur 404.
        #   "$uri" dans la configuration Nginx représente la partie de l'URL
        #   demandée par le client et est utilisé pour rechercher des fichiers correspondants

        
        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
              	fastcgi_pass wordpress:9000;
        }

        #   Indique que cette config s'applique aux fichiers ayant une extension ".php". "~" pour sensibiliser à la casse.
        
        #   Indique à Nginx de gérer les fichiers PHP en incluant le fichier "fastcgi-php.conf" qui contient les paramètres
        #   de traitement FastCGI spécifiques à PHP. Les requêtes PHP sont ensuite transmises
        #   à un serveur FastCGI spécifié via la directive "fastcgi_pass". Utile pour permettre à Nginx de traiter les scripts PHP
        #   en utilisant un serveur FastCGI dédié, tel que PHP-FPM, pour fournir une exécution rapide et efficace des scripts PHP
        #   Cette config est utilisée pour permettre à Nginx de traiter les scripts PHP en utilisant un serveur FastCGI dédié,
        #   tel que PHP-FPM, pour fournir une exécution rapide et efficace des scripts PHP.

        location ~ /\.ht {
              deny all;
        }
        #   Empêche l'accès direct aux fichiers ".htaccess". Ils contiennent svt des directives sensibles qui peuvent affecter
        #   la config et le fonctionnement d'un serveur Apache. (Logiciel serveur HTTP open source qui prend en charge diverses
        #   fonctionnalités, telles que la gestion des requêtes web, l'interprétation des fichiers PHP, la gestion des fichiers .htaccess,
        #   la réécriture d'URL, etc.)
}